version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: treinetic_taskmanager
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  spring-backend:
    build: .
    container_name: spring-backend
    ports:
      - "8081:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/treinetic_taskmanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql-db
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
